### ISSUE TITLE
Issues on Symbol in RFQ tile - "Hard-code" to USDT/USD

### ISSUE THREAD

**Issue by cjmiller81** [cjmiller81/TDA_GUIv2#46]
**CURRENT BUG ISSUE TO REVIEW**
Currently there is some bug happening in the app, if you open the RFQ page, you see this:
![image](https://github.com/cjmiller81/TDA_GUIv2/assets/23350533/f5ad6097-cc5f-4e82-8de6-65968f546611)
Click RFQ now though and get this:
![image](https://github.com/cjmiller81/TDA_GUIv2/assets/23350533/1b2502ff-707d-4f9e-9e28-2bb617889db7)
then it stays that way after it expires
![image](https://github.com/cjmiller81/TDA_GUIv2/assets/23350533/b9835ec4-cf55-4c6c-a8e6-528b6000065d)

It seems there is an issue populating that based on the response from the API or some state tracking issue for the symbol dropdown. 

- [ ] Address bug and fix issue

**"HARD-CODE" FOR USDT/USD**
We really ONLY need USDT/USD to be the only symbol set in the actual RFQ tile now. We will likely be changing things on RFQ execution tile as well, so let's simplify a few things on this a bit for now:

- [x] Allow ONLY "USDT" in the first currency dropdown
- [x] Allow ONLY "USD" in the second currency dropdown
- [x] If easiest, simply hardcode "USDT/USD" as the `Symbol` in the "Symbol" field in the RFQ Tile (see 1 on #10 )

**Comment by mohsinds** [comment]
first currency will accept only USDT from dropdown while second currency will accept USD only
also fixed the issue USDT/null, now it's showing the actual values USDT/USD
*no hardcode values are used
