### ISSUE TITLE
RFQ Tile Updates

### ISSUE THREAD

**Issue by cjmiller81** [cjmiller81/TDA_GUIv2#47]
Need to make a few changes to the RFQ Tile. Please see below and advise any questions of if anything is unclear. 

- [x] Change default timer to 10 seconds (also can you advise where you setting this value from, we need to likely change that)
- [x] If a Trade is confirmed (clicking Yes on either the Buy or Sell), the RFQ should be stopped. Currently the RFQ continues to run: 
![image](https://github.com/cjmiller81/TDA_GUIv2/assets/23350533/8330d9f1-6fcb-49a8-a1a6-2e56469a4040)
- [x] Currently both the Buy and Sell Confirmation screens can appear at the same time. We don't want that. If one is displayed, we should disable the other side and require the user to click "No" (or a similar solution) 
![image](https://github.com/cjmiller81/TDA_GUIv2/assets/23350533/4c9779a2-cadd-4fbd-9709-491d0e951e4d)
- [ ] Can we increase the font size for both the `Currency` and `OrderQty` (see 2 & 3 here: #10). Something closer to this: 
![image](https://github.com/cjmiller81/TDA_GUIv2/assets/23350533/a2bfcac8-a443-43be-9d69-a894d5900e87)
- [ ] The `OrderQty`input should also be set to a double, and we need to allow rounding of 5 decimals.

**Comment by mohsinds** [comment]
you can change the timer in
Tile.tsx ==> progBar() => line number 188
